'use strict';

angular.module('emojilizerApp').factory('emojiService', function () {
	// Private

	var emojis = [
{ words: ['mountain bicyclist', 'mountainbike', 'mountain bike', 'MTB'], emoji: 0x1f6b5 },
{ words: ['collision', 'boom', 'explosion', 'explode'], emoji: 0x1f4a5 },
{ words: ['hooray', 'applause', 'clapping', 'clap'], emoji: 0x1f44f },
{ words: ['older woman', 'old woman', 'grandma'], emoji: 0x1f475 },
{ words: ['bicyclist', 'bicycling', 'cycling'], emoji: 0x1f6b4 },
{ words: ['santa claus', 'father christmas'], emoji: 0x1f385 },
{ words: ['beetle', 'ladybug', 'lady beetle'], emoji: 0x1f41e },
{ words: ['older man', 'old man', 'grandpa'], emoji: 0x1f474 },
{ words: ['grimacing', 'grimace', 'oh no'], emoji: 0x1f62c },
{ words: ['broken heart', 'heartbreak'], emoji: 0x1f494 },
{ words: ['disappointed', 'disappoint'], emoji: 0x1f61e },
{ words: ['heartbeat', 'beating heart'], emoji: 0x1f493 },
{ words: ['open book', 'read', 'reading'], emoji: 0x1f4d6 },
{ words: ['thought', 'think', 'thinking'], emoji: 0x1f4ad },
{ words: ['antenna', 'satellite dish'], emoji: 0x1f4e1 },
{ words: ['birthday cake', 'birthday'], emoji: 0x1f382 },
{ words: ['pensive', 'sad', 'depressed'], emoji: 0x1f614 },
{ words: ['chequered flag', 'finish'], emoji: 0x1f3c1 },
{ words: ['love letter', 'love mail'], emoji: 0x1f48c },
{ words: ['computer', 'PC', 'desktop'], emoji: 0x1f4bb },
{ words: ['gem', 'diamond', 'crystal'], emoji: 0x1f48e },
{ words: ['office', 'offices', 'work'], emoji: 0x1f3e2 },
{ words: ['smile', 'smiling', 'happy'], emoji: 0x1f600 },
{ words: ['store', 'shopping', 'shop'], emoji: 0x1f3ea },
{ words: ['biceps', 'muscle', 'flex'], emoji: 0x1f4aa },
{ words: ['graduation', 'graduate'], emoji: 0x1f393 },
{ words: ['card index', 'rolodex'], emoji: 0x1f4c7 },
{ words: ['confused', 'confusing'], emoji: 0x1f615 },
{ words: ['fries', 'french fries'], emoji: 0x1f35f },
{ words: ['glasses', 'eyeglasses'], emoji: 0x1f453 },
{ words: ['ice cream', 'icecream'], emoji: 0x1f368 },
{ words: ['nail polish', 'polish'], emoji: 0x1f485 },
{ words: ['open lock', 'unlocked'], emoji: 0x1f513 },
{ words: ['police car', 'cop car'], emoji: 0x1f693 },
{ words: ['skull', 'death', 'bones'], emoji: 0x1f480 },
{ words: ['unamused', 'not happy'], emoji: 0x1f612 },
{ words: ['file folder', 'files'], emoji: 0x1f4c1 },
{ words: ['poultry', 'drumstick'], emoji: 0x1f357 },
{ words: ['american football'], emoji: 0x1f3c8 },
{ words: ['forbid', 'forbidden'], emoji: 0x26d4 },
{ words: ['incoming envelope'], emoji: 0x1f4e8 },
{ words: ['sparkle', 'sparkles'], emoji: 0x2728 },
{ words: ['bikini', 'swimsuit'], emoji: 0x1f459 },
{ words: ['cherries', 'cherry'], emoji: 0x1f352 },
{ words: ['flower', 'hibiscus'], emoji: 0x1f33a },
{ words: ['flowers', 'bouquet'], emoji: 0x1f490 },
{ words: ['restroom', 'toilet'], emoji: 0x1f6bb },
{ words: ['revolving hearts'], emoji: 0x1f49e },
{ words: ['spaghetti', 'pasta'], emoji: 0x1f35d },
{ words: ['speaking', 'speech'], emoji: 0x1f4ac },
{ words: ['heard', 'hear', 'ear'], emoji: 0x1f442 },
{ words: ['closed umbrella'], emoji: 0x1f302 },
{ words: ['cyclone', 'spiral'], emoji: 0x1f300 },
{ words: ['house', 'building'], emoji: 0x1f3e0 },
{ words: ['keyboard', 'piano'], emoji: 0x1f3b9 },
{ words: ['microphone', 'mic'], emoji: 0x1f3a4 },
{ words: ['newspaper', 'news'], emoji: 0x1f4f0 },
{ words: ['palm', 'palm tree'], emoji: 0x1f334 },
{ words: ['pine decoration'], emoji: 0x1f38d },
{ words: ['shit', 'poo', 'poop'], emoji: 0x1f4a9 },
{ words: ['sleeping', 'sleep'], emoji: 0x1f634 },
{ words: ['smirking', 'smirk'], emoji: 0x1f60f },
{ words: ['snowflake', 'snow'], emoji: 0x2744 },
{ words: ['sparkling heart'], emoji: 0x1f496 },
{ words: ['sunrise', 'sunset'], emoji: 0x1f305 },
{ words: ['time', 'hourglass'], emoji: 0x231b },
{ words: ['bag', 'briefcase'], emoji: 0x1f4bc },
{ words: ['battery', 'power'], emoji: 0x1f50b },
{ words: ['bicycle', 'cycle'], emoji: 0x1f6b2 },
{ words: ['boat', 'sailboat'], emoji: 0x26f5 },
{ words: ['cherry blossom'], emoji: 0x1f338 },
{ words: ['christmas tree'], emoji: 0x1f384 },
{ words: ['evergreen tree'], emoji: 0x1f332 },
{ words: ['grinning', 'grin'], emoji: 0x1f604 },
{ words: ['noodles', 'ramen'], emoji: 0x1f35c },
{ words: ['pushpin', 'where'], emoji: 0x1f4cd },
{ words: ['roller coaster'], emoji: 0x1f3a2 },
{ words: ['smoke', 'smoking'], emoji: 0x1f6ac },
{ words: ['speaker', 'sound'], emoji: 0x1f508 },
{ words: ['TV', 'television'], emoji: 0x1f4fa },
{ words: ['womans clothes'], emoji: 0x1f45a },
{ words: ['alien monster'], emoji: 0x1f47e },
{ words: ['bee', 'honeybee'], emoji: 0x1f41d },
{ words: ['bookmark tabs'], emoji: 0x1f4d1 },
{ words: ['droplet', 'drop'], emoji: 0x1f4a7 },
{ words: ['entertainment'], emoji: 0x1f3ad },
{ words: ['growing heart'], emoji: 0x1f497 },
{ words: ['mail', 'postbox'], emoji: 0x1f4ee },
{ words: ['nut', 'chestnut'], emoji: 0x1f330 },
{ words: ['present', 'gift'], emoji: 0x1f381 },
{ words: ['shoe', 'sneaker'], emoji: 0x1f45e },
{ words: ['sweaty', 'sweat'], emoji: 0x1f4a6 },
{ words: ['syringe', 'shot'], emoji: 0x1f489 },
{ words: ['tropical fish'], emoji: 0x1f420 },
{ words: ['water buffalo'], emoji: 0x1f403 },
{ words: ['winking', 'wink'], emoji: 0x1f609 },
{ words: ['clock', 'watch'], emoji: 0x231a },
{ words: ['construction'], emoji: 0x1f6a7 },
{ words: ['crystal ball'], emoji: 0x1f52e },
{ words: ['dizzy symbol'], emoji: 0x1f4ab },
{ words: ['ferris wheel'], emoji: 0x1f3a1 },
{ words: ['fried shrimp'], emoji: 0x1f364 },
{ words: ['horse racing'], emoji: 0x1f3c7 },
{ words: ['leaf', 'leaves'], emoji: 0x1f342 },
{ words: ['left luggage'], emoji: 0x1f6c5 },
{ words: ['mobile phone'], emoji: 0x1f4f1 },
{ words: ['movie camera'], emoji: 0x1f3a5 },
{ words: ['music', 'sound'], emoji: 0x1f3b5 },
{ words: ['party popper'], emoji: 0x1f389 },
{ words: ['purple heart'], emoji: 0x1f49c },
{ words: ['radio button'], emoji: 0x1f518 },
{ words: ['rice cracker'], emoji: 0x1f358 },
{ words: ['slot machine'], emoji: 0x1f3b0 },
{ words: ['top hat', 'hat'], emoji: 0x1f3a9 },
{ words: ['video camera'], emoji: 0x1f4f9 },
{ words: ['white flower'], emoji: 0x1f4ae },
{ words: ['alarm clock'], emoji: 0x23f0 },
{ words: ['baby bottle'], emoji: 0x1f37c },
{ words: ['baby symbol'], emoji: 0x1f6bc },
{ words: ['coffee', 'tea'], emoji: 0x2615 },
{ words: ['credit card'], emoji: 0x1f4b3 },
{ words: ['fire engine'], emoji: 0x1f692 },
{ words: ['fire', 'flame'], emoji: 0x1f525 },
{ words: ['hit', 'target'], emoji: 0x1f3af },
{ words: ['mens symbol'], emoji: 0x1f6b9 },
{ words: ['mouth', 'kiss'], emoji: 0x1f444 },
{ words: ['postal horn'], emoji: 0x1f4ef },
{ words: ['sagittarius'], emoji: 0x2650 },
{ words: ['snowboarder'], emoji: 0x1f3c2 },
{ words: ['woman', 'lady'], emoji: 0x1f469 },
{ words: ['astonished'], emoji: 0x1f632 },
{ words: ['automobile'], emoji: 0x1f698 },
{ words: ['automobile'], emoji: 0x1f697 },
{ words: ['baby angel'], emoji: 0x1f47c },
{ words: ['baby chick'], emoji: 0x1f424 },
{ words: ['blue heart'], emoji: 0x1f499 },
{ words: ['confounded'], emoji: 0x1f616 },
{ words: ['cross mark'], emoji: 0x274c },
{ words: ['curly loop'], emoji: 0x27b0 },
{ words: ['fart', 'dash'], emoji: 0x1f4a8 },
{ words: ['flashlight'], emoji: 0x1f526 },
{ words: ['footprints'], emoji: 0x1f463 },
{ words: ['helicopter'], emoji: 0x1f681 },
{ words: ['imp', 'devil'], emoji: 0x1f47f },
{ words: ['inbox tray'], emoji: 0x1f4e5 },
{ words: ['kiss', 'lips'], emoji: 0x1f48b },
{ words: ['light rail'], emoji: 0x1f688 },
{ words: ['locomotive'], emoji: 0x1f682 },
{ words: ['love hotel'], emoji: 0x1f3e9 },
{ words: ['maple leaf'], emoji: 0x1f341 },
{ words: ['microscope'], emoji: 0x1f52c },
{ words: ['name badge'], emoji: 0x1f4db },
{ words: ['no comment'], emoji: 0x1f611 },
{ words: ['strawberry'], emoji: 0x1f353 },
{ words: ['trolleybus'], emoji: 0x1f68e },
{ words: ['video game'], emoji: 0x1f3ae },
{ words: ['water wave'], emoji: 0x1f30a },
{ words: ['watermelon'], emoji: 0x1f349 },
{ words: ['wind chime'], emoji: 0x1f390 },
{ words: ['womans hat'], emoji: 0x1f452 },
{ words: ['ambulance'], emoji: 0x1f691 },
{ words: ['aubergine'], emoji: 0x1f346 },
{ words: ['billiards'], emoji: 0x1f3b1 },
{ words: ['capricorn'], emoji: 0x2651 },
{ words: ['chocolate'], emoji: 0x1f36b },
{ words: ['clipboard'], emoji: 0x1f4cb },
{ words: ['crocodile'], emoji: 0x1f40a },
{ words: ['die', 'dice'], emoji: 0x1f3b2 },
{ words: ['dromedary'], emoji: 0x1f42a },
{ words: ['fireworks'], emoji: 0x1f386 },
{ words: ['fuel pump'], emoji: 0x26fd },
{ words: ['halloween'], emoji: 0x1f383 },
{ words: ['hamburger'], emoji: 0x1f354 },
{ words: ['headphone'], emoji: 0x1f3a7 },
{ words: ['megaphone'], emoji: 0x1f4e3 },
{ words: ['milky way'], emoji: 0x1f30c },
{ words: ['money bag'], emoji: 0x1f4b0 },
{ words: ['ophiuchus'], emoji: 0x26ce },
{ words: ['paperclip'], emoji: 0x1f4ce },
{ words: ['pineapple'], emoji: 0x1f34d },
{ words: ['rice ball'], emoji: 0x1f359 },
{ words: ['saxophone'], emoji: 0x1f3b7 },
{ words: ['speedboat'], emoji: 0x1f6a4 },
{ words: ['sunflower'], emoji: 0x1f33b },
{ words: ['tangerine'], emoji: 0x1f34a },
{ words: ['telescope'], emoji: 0x1f52d },
{ words: ['eyes', 'see'], emoji: 0x1f440 },
{ words: ['airplane'], emoji: 0x2708 },
{ words: ['aquarius'], emoji: 0x2652 },
{ words: ['blowfish'], emoji: 0x1f421 },
{ words: ['bookmark'], emoji: 0x1f516 },
{ words: ['bus stop'], emoji: 0x1f68f },
{ words: ['calendar'], emoji: 0x1f4c5 },
{ words: ['calendar'], emoji: 0x1f4c6 },
{ words: ['cocktail'], emoji: 0x1f378 },
{ words: ['delivery'], emoji: 0x1f69a },
{ words: ['doughnut'], emoji: 0x1f369 },
{ words: ['elephant'], emoji: 0x1f418 },
{ words: ['envelope'], emoji: 0x2709 },
{ words: ['fountain'], emoji: 0x26f2 },
{ words: ['hash key'], emoji: 0x20e3 },
{ words: ['hatching'], emoji: 0x1f423 },
{ words: ['hospital'], emoji: 0x1f3e5 },
{ words: ['lipstick'], emoji: 0x1f484 },
{ words: ['lollipop'], emoji: 0x1f36d },
{ words: ['love you'], emoji: 0x1f60d },
{ words: ['monorail'], emoji: 0x1f69d },
{ words: ['mushroom'], emoji: 0x1f344 },
{ words: ['notebook'], emoji: 0x1f4d3 },
{ words: ['pig nose'], emoji: 0x1f43d },
{ words: ['princess'], emoji: 0x1f478 },
{ words: ['relieved'], emoji: 0x1f60c },
{ words: ['scorpius'], emoji: 0x264f },
{ words: ['seedling'], emoji: 0x1f331 },
{ words: ['sleeping'], emoji: 0x1f4a4 },
{ words: ['tram car'], emoji: 0x1f68b },
{ words: ['anguish'], emoji: 0x1f627 },
{ words: ['balloon'], emoji: 0x1f388 },
{ words: ['bathtub'], emoji: 0x1f6c1 },
{ words: ['blossom'], emoji: 0x1f33c },
{ words: ['bowling'], emoji: 0x1f3b3 },
{ words: ['CD', 'DVD'], emoji: 0x1f4bf },
{ words: ['chicken'], emoji: 0x1f414 },
{ words: ['cooking'], emoji: 0x1f373 },
{ words: ['custard'], emoji: 0x1f36e },
{ words: ['dolphin'], emoji: 0x1f42c },
{ words: ['factory'], emoji: 0x1f3ed },
{ words: ['fearful'], emoji: 0x1f628 },
{ words: ['flushed'], emoji: 0x1f633 },
{ words: ['haircut'], emoji: 0x1f487 },
{ words: ['hamster'], emoji: 0x1f439 },
{ words: ['handbag'], emoji: 0x1f45c },
{ words: ['kissing'], emoji: 0x1f617 },
{ words: ['kissing'], emoji: 0x1f48f },
{ words: ['leopard'], emoji: 0x1f406 },
{ words: ['massage'], emoji: 0x1f486 },
{ words: ['minibus'], emoji: 0x1f690 },
{ words: ['neutral'], emoji: 0x1f610 },
{ words: ['octopus'], emoji: 0x1f419 },
{ words: ['package'], emoji: 0x1f4e6 },
{ words: ['palette'], emoji: 0x1f3a8 },
{ words: ['penguin'], emoji: 0x1f427 },
{ words: ['pouting'], emoji: 0x1f621 },
{ words: ['pushpin'], emoji: 0x1f4cc },
{ words: ['railway'], emoji: 0x1f683 },
{ words: ['rainbow'], emoji: 0x1f308 },
{ words: ['rooster'], emoji: 0x1f413 },
{ words: ['rowboat'], emoji: 0x1f6a3 },
{ words: ['running'], emoji: 0x1f45f },
{ words: ['satchel'], emoji: 0x1f392 },
{ words: ['sparkle'], emoji: 0x2747 },
{ words: ['station'], emoji: 0x1f689 },
{ words: ['swimmer'], emoji: 0x1f3ca },
{ words: ['tractor'], emoji: 0x1f69c },
{ words: ['trumpet'], emoji: 0x1f3ba },
{ words: ['volcano'], emoji: 0x1f30b },
{ words: ['warning'], emoji: 0x26a0 },
{ words: ['wedding'], emoji: 0x1f492 },
{ words: ['worried'], emoji: 0x1f61f },
{ words: ['anchor'], emoji: 0x2693 },
{ words: ['banana'], emoji: 0x1f34c },
{ words: ['cactus'], emoji: 0x1f335 },
{ words: ['camera'], emoji: 0x1f4f7 },
{ words: ['cancer'], emoji: 0x264b },
{ words: ['church'], emoji: 0x26ea },
{ words: ['circus'], emoji: 0x1f3aa },
{ words: ['cookie'], emoji: 0x1f36a },
{ words: ['crying'], emoji: 0x1f622 },
{ words: ['dragon'], emoji: 0x1f409 },
{ words: ['dragon'], emoji: 0x1f432 },
{ words: ['drinks'], emoji: 0x1f379 },
{ words: ['family'], emoji: 0x1f46a },
{ words: ['gemini'], emoji: 0x264a },
{ words: ['goblin'], emoji: 0x1f47a },
{ words: ['grapes'], emoji: 0x1f347 },
{ words: ['guitar'], emoji: 0x1f3b8 },
{ words: ['hammer'], emoji: 0x1f528 },
{ words: ['hushed'], emoji: 0x1f62f },
{ words: ['kimono'], emoji: 0x1f458 },
{ words: ['ledger'], emoji: 0x1f4d2 },
{ words: ['monkey'], emoji: 0x1f435 },
{ words: ['monkey'], emoji: 0x1f412 },
{ words: ['outbox'], emoji: 0x1f4e4 },
{ words: ['pencil'], emoji: 0x270f },
{ words: ['pisces'], emoji: 0x2653 },
{ words: ['pistol'], emoji: 0x1f52b },
{ words: ['police'], emoji: 0x1f46e },
{ words: ['poodle'], emoji: 0x1f429 },
{ words: ['rabbit'], emoji: 0x1f430 },
{ words: ['rabbit'], emoji: 0x1f407 },
{ words: ['ribbon'], emoji: 0x1f380 },
{ words: ['rocket'], emoji: 0x1f680 },
{ words: ['sandal'], emoji: 0x1f461 },
{ words: ['school'], emoji: 0x1f3eb },
{ words: ['scroll'], emoji: 0x1f4dc },
{ words: ['shower'], emoji: 0x1f6bf },
{ words: ['sleepy'], emoji: 0x1f62a },
{ words: ['soccer'], emoji: 0x26bd },
{ words: ['surfer'], emoji: 0x1f3c4 },
{ words: ['taurus'], emoji: 0x2649 },
{ words: ['ticket'], emoji: 0x1f3ab },
{ words: ['toilet'], emoji: 0x1f6bd },
{ words: ['tomato'], emoji: 0x1f345 },
{ words: ['tongue'], emoji: 0x1f445 },
{ words: ['trophy'], emoji: 0x1f3c6 },
{ words: ['tshirt'], emoji: 0x1f455 },
{ words: ['turtle'], emoji: 0x1f422 },
{ words: ['violin'], emoji: 0x1f3bb },
{ words: ['wrench'], emoji: 0x1f527 },
{ words: ['alien'], emoji: 0x1f47d },
{ words: ['anger'], emoji: 0x1f4a2 },
{ words: ['angry'], emoji: 0x1f620 },
{ words: ['apple'], emoji: 0x1f34e },
{ words: ['apple'], emoji: 0x1f34f },
{ words: ['aries'], emoji: 0x2648 },
{ words: ['bento'], emoji: 0x1f371 },
{ words: ['books'], emoji: 0x1f4da },
{ words: ['bread'], emoji: 0x1f35e },
{ words: ['camel'], emoji: 0x1f42b },
{ words: ['candy'], emoji: 0x1f36c },
{ words: ['cloud'], emoji: 0x2601 },
{ words: ['crown'], emoji: 0x1f451 },
{ words: ['dance'], emoji: 0x1f483 },
{ words: ['dizzy'], emoji: 0x1f635 },
{ words: ['dress'], emoji: 0x1f457 },
{ words: ['email'], emoji: 0x1f4e7 },
{ words: ['foggy'], emoji: 0x1f301 },
{ words: ['frown'], emoji: 0x1f64d },
{ words: ['ghost'], emoji: 0x1f47b },
{ words: ['graph'], emoji: 0x1f4ca },
{ words: ['guard'], emoji: 0x1f482 },
{ words: ['honey'], emoji: 0x1f36f },
{ words: ['horse'], emoji: 0x1f434 },
{ words: ['horse'], emoji: 0x1f40e },
{ words: ['hotel'], emoji: 0x1f3e8 },
{ words: ['jeans'], emoji: 0x1f456 },
{ words: ['knife'], emoji: 0x1f52a },
{ words: ['koala'], emoji: 0x1f428 },
{ words: ['lemon'], emoji: 0x1f34b },
{ words: ['libra'], emoji: 0x264e },
{ words: ['melon'], emoji: 0x1f348 },
{ words: ['metro'], emoji: 0x1f687 },
{ words: ['mouse'], emoji: 0x1f42d },
{ words: ['mouse'], emoji: 0x1f401 },
{ words: ['pager'], emoji: 0x1f4df },
{ words: ['panda'], emoji: 0x1f43c },
{ words: ['peach'], emoji: 0x1f351 },
{ words: ['phone'], emoji: 0x1f4de },
{ words: ['pouch'], emoji: 0x1f45d },
{ words: ['purse'], emoji: 0x1f45b },
{ words: ['radio'], emoji: 0x1f4fb },
{ words: ['right'], emoji: 0x27a1 },
{ words: ['rugby'], emoji: 0x1f3c9 },
{ words: ['ruler'], emoji: 0x1f4cf },
{ words: ['sheep'], emoji: 0x1f411 },
{ words: ['shell'], emoji: 0x1f41a },
{ words: ['snail'], emoji: 0x1f40c },
{ words: ['snake'], emoji: 0x1f40d },
{ words: ['spark'], emoji: 0x1f50c },
{ words: ['sushi'], emoji: 0x1f363 },
{ words: ['tiger'], emoji: 0x1f42f },
{ words: ['tiger'], emoji: 0x1f405 },
{ words: ['tired'], emoji: 0x1f62b },
{ words: ['train'], emoji: 0x1f686 },
{ words: ['tulip'], emoji: 0x1f337 },
{ words: ['video'], emoji: 0x1f4fc },
{ words: ['virgo'], emoji: 0x264d },
{ words: ['weary'], emoji: 0x1f629 },
{ words: ['whale'], emoji: 0x1f433 },
{ words: ['whale'], emoji: 0x1f40b },
{ words: ['baby'], emoji: 0x1f476 },
{ words: ['bank'], emoji: 0x1f3e6 },
{ words: ['bath'], emoji: 0x1f6c0 },
{ words: ['bear'], emoji: 0x1f43b },
{ words: ['beer'], emoji: 0x1f37a },
{ words: ['bell'], emoji: 0x1f514 },
{ words: ['bird'], emoji: 0x1f426 },
{ words: ['boar'], emoji: 0x1f417 },
{ words: ['bomb'], emoji: 0x1f4a3 },
{ words: ['book'], emoji: 0x1f4d5 },
{ words: ['boot'], emoji: 0x1f462 },
{ words: ['cake'], emoji: 0x1f370 },
{ words: ['door'], emoji: 0x1f6aa },
{ words: ['down'], emoji: 0x2b07 },
{ words: ['fish'], emoji: 0x1f41f },
{ words: ['fist'], emoji: 0x270a },
{ words: ['frog'], emoji: 0x1f438 },
{ words: ['girl'], emoji: 0x1f467 },
{ words: ['goat'], emoji: 0x1f410 },
{ words: ['hand'], emoji: 0x270b },
{ words: ['herb'], emoji: 0x1f33f },
{ words: ['kids'], emoji: 0x1f46b },
{ words: ['left'], emoji: 0x2b05 },
{ words: ['link'], emoji: 0x1f517 },
{ words: ['lock'], emoji: 0x1f512 },
{ words: ['love'], emoji: 0x1f495 },
{ words: ['memo'], emoji: 0x1f4dd },
{ words: ['moon'], emoji: 0x1f319 },
{ words: ['nose'], emoji: 0x1f443 },
{ words: ['oden'], emoji: 0x1f362 },
{ words: ['ogre'], emoji: 0x1f479 },
{ words: ['paws'], emoji: 0x1f43e },
{ words: ['pear'], emoji: 0x1f350 },
{ words: ['pill'], emoji: 0x1f48a },
{ words: ['pray'], emoji: 0x1f64f },
{ words: ['rice'], emoji: 0x1f35a },
{ words: ['ring'], emoji: 0x1f48d },
{ words: ['rose'], emoji: 0x1f339 },
{ words: ['save'], emoji: 0x1f4be },
{ words: ['seat'], emoji: 0x1f4ba },
{ words: ['ship'], emoji: 0x1f6a2 },
{ words: ['star'], emoji: 0x1f31f },
{ words: ['taxi'], emoji: 0x1f695 },
{ words: ['taxi'], emoji: 0x1f696 },
{ words: ['tent'], emoji: 0x26fa },
{ words: ['tram'], emoji: 0x1f68a },
{ words: ['tree'], emoji: 0x1f333 },
{ words: ['walk'], emoji: 0x1f6b6 },
{ words: ['wine'], emoji: 0x1f377 },
{ words: ['wolf'], emoji: 0x1f43a },
{ words: ['ant'], emoji: 0x1f41c },
{ words: ['boy'], emoji: 0x1f466 },
{ words: ['bug'], emoji: 0x1f41b },
{ words: ['bus'], emoji: 0x1f68c },
{ words: ['bus'], emoji: 0x1f68d },
{ words: ['cat'], emoji: 0x1f431 },
{ words: ['cat'], emoji: 0x1f408 },
{ words: ['cow'], emoji: 0x1f42e },
{ words: ['cow'], emoji: 0x1f404 },
{ words: ['dog'], emoji: 0x1f436 },
{ words: ['dog'], emoji: 0x1f415 },
{ words: ['dvd'], emoji: 0x1f4c0 },
{ words: ['fax'], emoji: 0x1f4e0 },
{ words: ['key'], emoji: 0x1f511 },
{ words: ['leo'], emoji: 0x264c },
{ words: ['man'], emoji: 0x1f468 },
{ words: ['pig'], emoji: 0x1f437 },
{ words: ['pig'], emoji: 0x1f416 },
{ words: ['ram'], emoji: 0x1f40f },
{ words: ['rat'], emoji: 0x1f400 },
{ words: ['run'], emoji: 0x1f3c3 },
{ words: ['tie'], emoji: 0x1f454 },
{ words: ['yes'], emoji: 0x1f44d },
{ words: ['no'], emoji: 0x1f44e },
{ words: ['ox'], emoji: 0x1f402 },
{ words: ['up'], emoji: 0x2b06 },
{ words: ['wc'], emoji: 0x1f6be },
	];

	//-------

	var stringFromCodePoint = function () {
		var chars = Array.prototype.slice.call(arguments);
		for (var i = chars.length; i-->0;) {
			var n = chars[i]-0x10000;
			if (n >= 0) {
				chars.splice(i, 1, 0xD800 + (n >> 10), 0xDC00 + (n & 0x3FF));
			}
		}
		return String.fromCharCode.apply(null, chars);
	};

	var emojiCodeToString = function (code) {
		return stringFromCodePoint(code);
	};

	// Public API here

	return {
		
		convert: function (text) {
			var newText = text;
			for (var e in emojis) {
				for (var w in emojis[e].words) {
					newText = newText.replace(new RegExp('\\b' + emojis[e].words[w] + '\\b', 'ig'), emojiCodeToString(emojis[e].emoji) );
				}
			}
			return newText;
		}

	};

});